trigger: none

stages:
  - stage: destroy
    jobs:
      - deployment: terraform_destroy
        environment: prod-destroy
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    terraform -chdir=environments/dev/platform init
                    terraform -chdir=environments/dev/platform destroy -auto-approve
                  displayName: Terraform destroy
