trigger: none

stages:
  - stage: apply
    jobs:
      - deployment: terraform_apply
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: terraform-plan
                - script: |
                    terraform -chdir=environments/dev/platform init
                    terraform -chdir=environments/dev/platform apply tfplan
                  displayName: Terraform apply saved plan
