trigger: none

stages:
  - stage: destroy
    jobs:
      - job: terraform_destroy
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              terraform -chdir=environments/dev/platform init
              terraform -chdir=environments/dev/platform destroy -auto-approve
            displayName: Terraform destroy
