trigger: none

stages:
  - stage: apply
    jobs:
      - deployment: terraform_apply
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    terraform -chdir=environments/dev/platform init
                    terraform -chdir=environments/dev/platform apply -auto-approve
                  displayName: Terraform apply
