name: terraform-apply

on:
  workflow_dispatch:
    inputs:
      stack_path:
        description: "Terraform stack path"
        required: true
        default: "environments/dev/platform"

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Build Artifact Name
        id: artifact_meta
        run: echo "name=terraform-plan-$(echo '${{ github.event.inputs.stack_path }}' | tr '/' '-')" >> "$GITHUB_OUTPUT"
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact_meta.outputs.name }}
          path: ${{ github.event.inputs.stack_path }}
      - name: Terraform Init
        run: terraform -chdir=${{ github.event.inputs.stack_path }} init
      - name: Terraform Apply Saved Plan
        run: terraform -chdir=${{ github.event.inputs.stack_path }} apply tfplan
